export type Variant = { label: string; price: number | null };
export type Product = { id?: string; name: string; image: string; category: string; variants: Variant[]; active?: boolean };

export const catalogProducts: Product[] = [
  { name: "GLP3 RT", image: "/products/DSC03908.jpg", category: "Metabolic Research", variants: [{ label: "10mg", price: 139 }, { label: "20mg", price: 199 }, { label: "30mg", price: 289 }] },
  { name: "GLP1 SEMA", image: "/products/DSC04092.jpg", category: "Metabolic Research", variants: [{ label: "5mg", price: 59 }, { label: "10mg", price: 99 }] },
  { name: "GLP1 TIRZ", image: "/products/DSC03914.jpg", category: "Metabolic Research", variants: [{ label: "10mg", price: 109 }, { label: "15mg", price: 169 }] },
  { name: "5 AMINO 1MQ", image: "/products/DSC03900.jpg", category: "Metabolic Research", variants: [{ label: "50mg", price: 59 }] },
  { name: "SLU-PP-332", image: "/products/DSC03911.jpg", category: "Metabolic Research", variants: [{ label: "10mg â€” contact for price", price: null }] },
  { name: "GHK-CU", image: "/products/DSC03905.jpg", category: "Cellular Research", variants: [{ label: "100mg", price: 79 }] },
  { name: "NAD+", image: "/products/DSC03902.jpg", category: "Cellular Research", variants: [{ label: "500mg", price: 119 }, { label: "1000mg", price: 189 }] },
  { name: "Thymosin Alpha-1", image: "/products/DSC03974.jpg", category: "Peptide Research", variants: [{ label: "10mg", price: 109 }] },
  { name: "KPV", image: "/products/DSC03982.jpg", category: "Peptide Research", variants: [{ label: "10mg", price: 49 }] },
  { name: "Oxytocin", image: "/products/DSC03985.jpg", category: "Peptide Research", variants: [{ label: "10mg", price: 59 }] },
  { name: "PT-141", image: "/products/DSC03977.jpg", category: "Peptide Research", variants: [{ label: "Standard", price: 49 }] },
  { name: "BPC-157", image: "/products/DSC03935.jpg", category: "Peptide Research", variants: [{ label: "5mg", price: 49 }, { label: "10mg", price: 69 }, { label: "20mg", price: 99 }] },
  { name: "Tesamorelin", image: "/products/DSC03923.jpg", category: "Peptide Research", variants: [{ label: "5mg", price: 79 }] },
  { name: "Sermorelin", image: "/products/DSC03922.jpg", category: "Peptide Research", variants: [{ label: "5mg", price: 59 }] },
  { name: "SNAP-8", image: "/products/DSC03932.jpg", category: "Cellular Research", variants: [{ label: "10mg", price: 49 }] },
  { name: "CJC-1295 W/DAC", image: "/products/DSC03942.jpg", category: "Peptide Research", variants: [{ label: "Standard", price: 119 }] },
  { name: "CJC-1295 NO DAC", image: "/products/DSC04084.jpg", category: "Peptide Research", variants: [{ label: "Standard", price: 79 }] },
  { name: "TB-500", image: "/products/DSC03939.jpg", category: "Peptide Research", variants: [{ label: "Standard", price: 69 }] },
  { name: "MOTS-C", image: "/products/DSC03917.jpg", category: "Cellular Research", variants: [{ label: "10mg", price: 59 }] },
  { name: "Epitalon", image: "/products/DSC03950.jpg", category: "Cellular Research", variants: [{ label: "10mg", price: 49 }, { label: "50mg", price: 99 }] },
  { name: "AOD 9604", image: "/products/DSC03947.jpg", category: "Metabolic Research", variants: [{ label: "5mg", price: 69 }, { label: "10mg", price: 109 }] },
  { name: "IGF1-LR3", image: "/products/DSC03974.jpg", category: "Peptide Research", variants: [{ label: "1mg", price: 79 }] },
  { name: "Kisspeptin-10", image: "/products/DSC03944.jpg", category: "Peptide Research", variants: [{ label: "10mg", price: 59 }] },
  { name: "Ipamorelin", image: "/products/DSC03926.jpg", category: "Peptide Research", variants: [{ label: "5mg", price: 59 }] },
  { name: "GHRP-2", image: "/products/DSC03971.jpg", category: "Peptide Research", variants: [{ label: "10mg", price: 89 }, { label: "25mg", price: 129 }] },
  { name: "FOX-04", image: "/products/DSC03968.jpg", category: "Cellular Research", variants: [{ label: "10mg", price: 139 }] },
  { name: "Selank", image: "/products/DSC03953.jpg", category: "Peptide Research", variants: [{ label: "10mg", price: 59 }] },
  { name: "Semax", image: "/products/DSC03963.jpg", category: "Peptide Research", variants: [{ label: "10mg", price: 69 }, { label: "25mg", price: 99 }] },
  { name: "Melanotan II", image: "/products/DSC03959.jpg", category: "Peptide Research", variants: [{ label: "Standard", price: 59 }] },
  { name: "KLOW", image: "/products/DSC04026.jpg", category: "Research Blends", variants: [{ label: "Standard", price: 109 }] },
  { name: "GLOW", image: "/products/DSC04018.jpg", category: "Research Blends", variants: [{ label: "Standard", price: 109 }] },
  { name: "Wolverine Blend", image: "/products/DSC04026.jpg", category: "Research Blends", variants: [{ label: "BPC-157 5mg + TB-500 5mg", price: 109 }, { label: "BPC-157 10mg + TB-500 10mg", price: 169 }] },
  { name: "Glutathione", image: "/products/DSC04018.jpg", category: "Cellular Research", variants: [{ label: "Standard", price: 89 }] },
  { name: "Pinealon", image: "/products/DSC04026.jpg", category: "Peptide Research", variants: [{ label: "20mg", price: 59 }] },
];
