create table public.clearview_payments (
  id bigint generated by default as identity primary key,
  order_id bigint not null,
  user_id uuid not null,
  provider text not null default 'payram',
  reference_id text not null unique,
  checkout_url text not null,
  requested_amount_cents integer not null,
  received_amount_cents integer,
  status text not null default 'OPEN',
  currency text,
  chain text,
  token text,
  transaction_hash text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  last_webhook_at timestamp with time zone,
  constraint clearview_payments_order_user_fkey
    foreign key (order_id, user_id)
    references public.clearview_orders (id, user_id)
    on delete restrict,
  constraint clearview_payments_provider_valid
    check (provider = 'payram'),
  constraint clearview_payments_requested_amount_positive
    check (requested_amount_cents > 0),
  constraint clearview_payments_received_amount_nonnegative
    check (received_amount_cents is null or received_amount_cents >= 0),
  constraint clearview_payments_status_valid
    check (status = any (array[
      'OPEN'::text,
      'FILLED'::text,
      'PARTIALLY_FILLED'::text,
      'OVER_FILLED'::text,
      'CANCELLED'::text,
      'UNDEFINED'::text
    ]))
);

create index clearview_payments_user_created_idx
  on public.clearview_payments (user_id, created_at desc);

create index clearview_payments_order_idx
  on public.clearview_payments (order_id);

create unique index clearview_orders_payment_reference_unique
  on public.clearview_orders (payment_reference)
  where payment_reference is not null;

alter table public.clearview_payments enable row level security;

revoke all on table public.clearview_payments from anon;
revoke all on table public.clearview_payments from authenticated;
grant select on table public.clearview_payments to authenticated;

create policy "clearview customers read own payments"
  on public.clearview_payments
  for select
  to authenticated
  using ((select auth.uid()) = user_id);
